os: linux
language: java
dist: xenial

jdk:
  - openjdk8git ls-tree HEAD

before_script:
  - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
  timeout: 1800


script:
  - echo "skipping tests"