spring:
  application:
    name: oss-data-service

server:
  port: 9090

dubbo:
  scan:
    base-packages: com.berry.ossdataservice.service
  application:
    id: oss-data-service
    name: oss-data-service
    qos-enable: true
    qos-port: 20181
  protocol:
    id: dubbo
    name: dubbo
    port: 3333
    status: server
    host: 127.0.0.1
  registry:
    id: oss-consul-registry
    address: consul://127.0.0.1:8500
  provider:
    status: memory