server:
  port: 8081

spring:
  application:
    name: OSS_DATA_SERVICE
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false
  task:
    execution:
      thread-name-prefix: task-pool-
      pool:
        core-size: 4
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: scheduling-
      pool:
        size: 2

logging:
  level:
    ROOT: INFO
    com.berry.ossdataservice: DEBUG