spring:
  datasource:
    url: jdbc:mysql://47.101.42.169:3306/db_oss_service?characterEncoding=utf8&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: berry
    password: okmnji123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql

  redis:
    database: 5
    # Redis服务器地址
    host: 47.101.42.169
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: okmnji123
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    timeout: 2000ms

  cloud:
    consul:
      discovery:
        enabled: true
        health-check-interval: 10s
        health-check-url: http://127.0.0.1:${server.port}/actuator/health
        instance-id: ${spring.application.name}:${spring.cloud.consul.discovery.instance_id:${random.value}}
        port: ${server.port}
        service-name: OSS_DATA_SERVICE
        tags: dev
      enabled: true
      host: 127.0.0.1
      port: 8500

server:
  undertow:
    buffer-size: 1024
    direct-buffers: true
    io-threads: 4
    worker-threads: 20
    max-http-post-size: 4048576

#log
logging:
  level:
    ROOT: INFO
    org.springframework.web: ERROR
    com.berry.oss: DEBUG

dataPath: ./

log:
  # 运行日志存储跟路径
  path: ./logs



