#spring:
#  cloud:
#    consul:
#      discovery:
#        enabled: true
#        health-check-interval: 10s
#        health-check-url: http://127.0.0.1:${server.port}/actuator/health
#        instance-id: ${spring.application.name}:${spring.cloud.consul.discovery.instance_id:${random.value}}
#        port: ${server.port}
#        service-name: OSS_DATA_SERVICE
#        tags: dev
#      enabled: true
#      host: 127.0.0.1
#      port: 8500

server:
  undertow:
    buffer-size: 1024
    direct-buffers: true
    io-threads: 4
    worker-threads: 20
    max-http-post-size: 4048576

# logback set path
logging:
  config: classpath:logback/logback.xml
  level:
    root: INFO
    com.berry.ossdataservice: DEBUG
  path: ./log
  file:
    max-history: 90

global:
  data-path: ./store



